# service: ufersa-biblioteca

# provider:
#   name: aws
#   runtime: nodejs20.x
#   region: us-east-1
#   stage: dev
#   environment:
#     IS_LOCAL: true
#     STAGE: dev

service: ufersa-biblioteca

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  environment:
    IS_LOCAL: true
    STAGE: dev
  httpApi:
    cors: true

functions:
  root:
    handler: src/crud.frontEndHandler
    events:
      - httpApi:
          path: /
          method: get

  criarSala:
    handler: src/crud.salasHandler
    events:
      - httpApi:
          path: /api/salas
          method: post
    environment:
      SALAS_TABLE: UFERSA_Salas

  listarSalas:
    handler: src/crud.salasHandler
    events:
      - httpApi:
          path: /api/salas
          method: get

  atualizarSala:
    handler: src/crud.salasHandler
    events:
      - httpApi:
          path: /api/salas/{id}
          method: put
    environment:
      SALAS_TABLE: UFERSA_Salas

  excluirSala:
    handler: src/crud.salasHandler
    events:
      - httpApi:
          path: /api/salas/{id}
          method: delete
    environment:
      SALAS_TABLE: UFERSA_Salas

  criarReserva:
    handler: src/crud.reservasHandler
    events:
      - httpApi:
          path: /api/reservas
          method: post
    environment:
      RESERVAS_TABLE: UFERSA_Reservas

  listarReservas:
    handler: src/crud.reservasHandler
    events:
      - httpApi:
          path: /api/reservas
          method: get
    environment:
      RESERVAS_TABLE: UFERSA_Reservas

  atualizarReserva:
    handler: src/crud.reservasHandler
    events:
      - httpApi:
          path: /api/reservas/{id}
          method: put
    environment:
      RESERVAS_TABLE: UFERSA_Reservas

  excluirReserva:
    handler: src/crud.reservasHandler
    events:
      - httpApi:
          path: /api/reservas/{id}
          method: delete
    environment:
      RESERVAS_TABLE: UFERSA_Reservas

  criarOcorrencia:
    handler: src/crud.ocorrenciasHandler
    events:
      - httpApi:
          path: /api/ocorrencias
          method: post
    environment:
      OCORRENCIAS_TABLE: UFERSA_Ocorrencias

  listarOcorrencias:
    handler: src/crud.ocorrenciasHandler
    events:
      - httpApi:
          path: /api/ocorrencias
          method: get
    environment:
      OCORRENCIAS_TABLE: UFERSA_Ocorrencias

  excluirOcorrencia:
    handler: src/crud.ocorrenciasHandler
    events:
      - httpApi:
          path: /api/ocorrencias/{id}
          method: delete
    environment:
      OCORRENCIAS_TABLE: UFERSA_Ocorrencias

  criarMaterial:
    handler: src/crud.inventarioHandler
    events:
      - httpApi:
          path: /api/materiais
          method: post
    environment:
      INVENTARIO_TABLE: UFERSA_Inventario

  listarMateriais:
    handler: src/crud.inventarioHandler
    events:
      - httpApi:
          path: /api/materiais
          method: get
    environment:
      INVENTARIO_TABLE: UFERSA_Inventario

  excluirMaterial:
    handler: src/crud.inventarioHandler
    events:
      - httpApi:
          path: /api/materiais/{id}
          method: delete

  gestaoSalas:
    handler: src/crud.frontEndHandler
    events:
      - httpApi:
          path: /gestao_salas/{proxy+}
          method: get

  reservasEmprestimos:
    handler: src/crud.frontEndHandler
    events:
      - httpApi:
          path: /reservas_emprestimos/{proxy+}
          method: get

  iaRelatorios:
    handler: src/crud.frontEndHandler
    events:
      - httpApi:
          path: /ia_relatorios/{proxy+}
          method: get

  painelInstitucional:
    handler: src/crud.frontEndHandler
    events:
      - httpApi:
          path: /painel_institucional/{proxy+}
          method: get

  inventario:
    handler: src/crud.frontEndHandler
    events:
      - httpApi:
          path: /inventario/{proxy+}
          method: get

  ocorrencias:
    handler: src/crud.frontEndHandler
    events:
      - httpApi:
          path: /ocorrencias/{proxy+}
          method: get

  frontEnd:
    handler: src/crud.frontEndHandler
    events:
      - httpApi:
          path: /gestao_salas/code.html
          method: get
      - httpApi:
          path: /painel_institucional/code.html
          method: get
      - httpApi:
          path: /reservas_emprestimos/code.html
          method: get
      - httpApi:
          path: /ia_relatorios/code.html
          method: get
      - httpApi:
          path: /inventario/code.html
          method: get
      - httpApi:
          path: /ocorrencias/code.html
          method: get

  staticJs:
    handler: src/crud.frontEndHandler
    events:
      - httpApi:
          path: /js/crud_salas.js
          method: get
      - httpApi:
          path: /js/crud_reservas.js
          method: get
      - httpApi:
          path: /js/crud_materiais.js
          method: get
      - httpApi:
          path: /js/api.js
          method: get
      - httpApi:
          path: /js/app.js
          method: get

  staticAssets:
    handler: src/crud.staticHandler
    events:
      - httpApi:
          path: /js/{file}
          method: get

  staticAssetsData:
    handler: src/crud.staticHandler
    events:
      - httpApi:
          path: /data/{file}
          method: get

package:
  individually: false
  patterns:
    - '!**'
    - src/**

plugins:
  - serverless-offline

custom:
  serverlessOffline:
    httpPort: 3003